[package]
name = "zsp-playground"
version = "0.1.0"
edition = "2021"

rustc-args = [ "--cfg" , "nolibs"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
zsp-core = { git = "https://github.com/CoolElectronics/zsp" }
console_error_panic_hook = "*"
